# Generated by Django 5.1 on 2024-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
