# Generated by Django 5.1 on 2024-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_userprofile_first_name_userprofile_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cardiology", "Cardiology"),
                    ("neurology", "Neurology"),
                    ("oncology", "Oncology"),
                    ("orthopedics", "Orthopedics"),
                    ("pediatrics", "Pediatrics"),
                    ("gynaecology", "Gynaecology"),
                    ("general", "General"),
                    ("emergency", "Emergency"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
