# Generated by Django 5.1 on 2024-08-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_userprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
