# Generated by Django 5.1 on 2024-08-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hospital",
            "0007_userprofile_address_userprofile_age_userprofile_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="doctor_availability",
            field=models.BooleanField(default=False),
        ),
    ]
