# Generated by Django 5.1 on 2024-08-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0008_userprofile_doctor_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="dob",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateTimeField(null=True),
        ),
    ]
