# Generated by Django 5.1 on 2024-08-22 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0009_appointment_dob_alter_appointment_appointment_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_doctor",
                to="hospital.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_patient",
                to="hospital.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="CheckupDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prescription", models.TextField()),
                ("observations", models.TextField()),
                ("next_visit_date", models.DateField()),
                ("checkup_status", models.BooleanField(default=True)),
                ("checkup_date", models.DateField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="checkup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.checkupdetails",
            ),
        ),
    ]
