# Generated by Django 5.1 on 2024-08-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hospital",
            "0010_alter_appointment_doctor_alter_appointment_patient_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="checkup",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_doctor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="checkupdetails",
            name="checkup_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checkupdetails",
            name="next_visit_date",
            field=models.DateField(null=True),
        ),
    ]
